---
os:
  - linux

language: c

compiler:
  - gcc

notifications:
  email: false

sudo: required
dist: xenial           # ubuntu 16.06, thankfully ignored in osx.

addons:
  apt:
    packages:
      - autopoint
      - diffutils
      - libpng-dev
      - libexif-dev
      - libtiff5-dev
      - libjpeg-dev
      - libxml2-dev
      - libbz2-dev
      - libpstoedit-dev
      - libmagickcore-dev
      - libfreetype6-dev
      - fakeroot
      - checkinstall

